# common vars
---
cloudimg_vm_id: 1600

proxmox_storage: "scd6"

proxmox_iso_storage_dir: "/mnt/nfs/iso/template/iso"
proxmox_cloudinit_dir: "/mnt/gfs/pve/snippets"
proxmox_vm_config_dir: "/etc/pve/local/qemu-server"
bootstrap_home_dir: "/root/automation"

cloudinit_username: "packer"
cloudinit_password: "packer"
cloudinit_default_network_interface: "vmbr0"
cloudinit_timezone: "Asia/Hong_Kong"
cloudinit_locale: "en"
