---
# common vars
arch: "amd64"

proxmox_storage: "scd6"
proxmox_iso_storage_dir: "/mnt/nfs/iso/template/iso"
proxmox_cloudinit_dir: "/mnt/gfs/pve/snippets"
proxmox_vm_config_dir: "/etc/pve/local/qemu-server"

bootstrap_home_dir: "/root/automation"

cloudinit_username: "packer"
cloudinit_password: "packer"
cloudinit_default_network_interface: "vmbr0"
cloudinit_timezone: "Asia/Hong_Kong"
cloudinit_locale: "en"

# cloudimg vars
cloudimg_vm_id: 1600

# packer-related vars
install_packer: no
packer_version: "1.10.0"
packer_release_url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_{{ arch }}.zip"
packer_release_filename: "packer_{{ packer_version }}_linux_{{ arch }}.zip"
packer_install_path: "/usr/local/bin"

# post-install tasks specific vars
post_install_locales:
  - en_US.UTF-8
  - zh_CN.UTF-8

# build vars
vm_id: 1610
vm_disk_size: "10G"

host_config: "../vars/host.pkvars.hcl"
#vm_config: "vars/debian-12.pkrvars.hcl"
vm_config: "vars/test.pkr.hcl"
vm_stable_config: "vars/stable.pkr.hcl"
boot_command_config: "vars/boot-command/ubuntu-2204.pkr.hcl"
playbook_file: "../playbooks/ubuntu_2204_server.yml"
#packer_template: "debian-proxmox-packer-template.pkr.hcl"
#template_name: "prod-debian-12-server-template"
template_name: "proxmox-iso.ubuntu-server-jammy"
