---
# --- STAGE 1: Build VM template (iso install)  ---
- name: "Build VM template"
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: ["stage1", "build_vm_template"]

  roles:
    - role: iso.packer.build/


