#   ____ _                 _   _____     _        _
#  / ___| | ___  _   _  __| | | ____|___| |_ __ _| |_ ___
# | |   | |/ _ \| | | |/ _` | |  _| / __| __/ _` | __/ _ \
# | |___| | (_) | |_| | (_| | | |___\__ \ || (_| | ||  __/
#  \____|_|\___/ \__,_|\__,_| |_____|___/\__\__,_|\__\___
#
# https://github.com/TechProber/cloud-estate
#
# Copyright (C) 2021-202 TechProber <https://github.com/TechProber>
#
# This is a open-source software, liscensed under the MIT License.
# See /License for more information.

name: Build and Deploy Collection

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build and Deploy Collection
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
